language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build . -t travis-env-node --build-arg SUPR_SCRT=${SUPR_SCRT} --build-arg NAME=${NAME}
  - docker tag travis-env-node saurabh0jha/travis-env-node:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push saurabh0jha/travis-env-node
